---
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'email-notifications'
receivers:
    - name: 'email-notifications'
      email_configs:
        - to: kathir@gmail.com
          from: Monitoring@gmail.com
          smarthost: smtp.gmail.com:587
          auth_username: kathir@gmail.com  # Replace with your actual username
          auth_identity: kathir@gmail.com  # Replace with your actual username
          auth_password: "wkpn qzlc jvsg mvlc  "  # Replace with your actual password
          send_resolved: true
inhibit_rules:
    - source_match:
        severity: 'critical'
      target_match:
        severity: 'warning'
      equal: ['alertname', 'dev', 'instance']
